### ISSUE TITLE
Idea: allow user to just use RIOTBASE

### ISSUE THREAD

**Issue by basilfx** [aabadie/riot-generator#1]
I tried to start an application, but it doesn't work. Would it be an option to ask the user to use the input?

```
(env) basilfx:test/ (master) $ riotgen application .
Application name (no space): test
Application brief description []: Test
Target board [native]:
Required modules (comma separated) []:
Required packages (comma separated) []:
Required board features (comma separated) []:
Author name [Bas Stottelaar]:
Author email [basstottelaar@gmail.com]:
Organization [Bas Stottelaar]:
RIOT base directory: ../../RIOT
Error: None
```

Something like:

```
RIOT base directory:
Dir does not exist. Do you want to continue [n]: y
```

**Comment by aabadie** [comment]
> RIOT base directory: ../../RIOT
> Error: None

Ok, this is a misuse of click on our side. The message should be explicit normally.

+1 for using RIOTBASE env if already defined.

**Comment by aabadie** [comment]
@basilfx I pushed 8a4998a that proposes a simple fix: if the given riotbase is invalid (from wizard, config file or env variable), a meaningful error message is returned.

BTW, now RIOTBASE environment variable is taken into account for application generation.
