### ISSUE TITLE
Missing variable declaration in template netdev

### ISSUE THREAD

**Issue by keestux** [aabadie/riot-generator#16]
The driver_netdev.c template is missing the declaration of the variable `state` in the function `_send`.

```
@@ -28,6 +28,7 @@
 static int _send(netdev_t *netdev, const iolist_t *iolist)
 {
     {{ driver.name }}_t *dev = ({{ driver.name }}_t *)netdev;
+    netopt_state_t state;
 
     uint8_t size = iolist_size(iolist);
```

Or maybe you want to combine the declaration and the assignment below.

**Comment by aabadie** [comment]
This is fixed by 009be2659960d1ec284c6c23ddf51cad0d57a1fb (sorry the latency)
