### ISSUE TITLE
Idea: notify where I can find the end result

### ISSUE THREAD

**Issue by basilfx** [aabadie/riot-generator#3]
As an end-user, I want to know where I can find the generated output if (especially if I don't specify the output directory).

For instance, when I am in the `RIOTBASE` folder, and I generate an example, it will be put in examples/<name>. But as a non-experience RIOT user, I might be confused and wonder where the results is.

Maybe something like this:

```
...
Application 'test' generated in `examples/test` with success!
```

**Comment by aabadie** [comment]
c420457 addresses your issue. Let me know if it works for you.
The pypi package hasn't been updated yet so you'll have to install the master version.

**Comment by aabadie** [comment]
This issue is also resolved so I'm closing it.
